engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
    exclude_fingerprints:
    # Ignore duplicated parse structure between INSERT and SELECT
    - d17377f9c9cc5c60cb8358974c8d6ba2
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.rb"
exclude_paths:
- "models/**/*"
- "plans/**/*"
- "schemas/**/*"
- "spec/**/*"
- "tmp/**/*"
- "workloads/**/*"
