Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Style/ClassAndModuleChildren:
  Exclude:
    - 'spec/**/*'

Style/SingleLineBlockParams:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic
